/**
 * Audit event taxonomy (dot-namespaced). Every PHI read/write path emits one
 * of these via @medpass/audit. Adding an action here is reviewed like an API
 * change — dashboards and audit-completeness tests key off these names.
 */
export const AUDIT_ACTIONS = [
  "auth.otp_requested",
  "auth.otp_verified",
  "auth.otp_failed",
  "auth.otp_locked",
  "auth.session_created",
  "auth.session_refreshed",
  "auth.session_revoked",
  "profile.created",
  "profile.updated",
  "profile.viewed_by_caregiver",
  "profile.claim_invited",
  "profile.claim_invite_cancelled",
  "profile.claimed",
  "consent.granted",
  "consent.revoked",
  "consent.enforced",
  "caregiver.invited",
  "caregiver.accepted",
  "caregiver.scope_changed",
  "caregiver.revoked",
  "caregiver.access_used",
  "caregiver.dependent_created",
  "caregiver.granted_on_claim",
  "allergy.created",
  "allergy.updated",
  "condition.created",
  "condition.updated",
  "glucose_reading.created",
  "glucose_reading.deleted",
  "checkup_record.created",
  "checkup_record.deleted",
  "medication.created",
  "medication.updated",
  "medication.status_changed",
  "medication.deleted",
  "medication.list_viewed",
  "medication.refill_recorded",
  "dose.recorded",
  "dose.correction_notice_created",
  "document.upload_authorized",
  "document.upload_completed",
  "document.downloaded",
  "extraction.processed",
  "extraction.field_confirmed",
  "extraction.field_rejected",
  "safety.evaluation_completed",
  "finding.viewed",
  "finding.acknowledged",
  "finding.action_recorded",
  "share.created",
  "share.accessed",
  "share.revoked",
  "notification.preferences_updated",
  "notification.dismissed",
  "notification.channel_revoked",
  "data.export_requested",
  "data.deletion_requested",
  "admin.audit_searched",
  "admin.login_succeeded",
  "admin.login_failed",
  "admin.mfa_enrolled",
  "admin.session_revoked",
  "admin.duties_changed",
  "admin.catalog_change_proposed",
  "admin.catalog_change_approved",
  "admin.catalog_change_rejected",
  "admin.content_change_proposed",
  "admin.content_change_approved",
  "admin.content_change_rejected",
  "admin.content_translation_proposed",
  "admin.content_translation_approved",
  "admin.content_translation_rejected",
  "admin.job_replayed",
  "admin.share_revoked",
  "admin.findings_viewed",
  "content.enrichment_drafted",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export type AuditActorType = "patient" | "caregiver" | "admin" | "system" | "share_visitor";
