/**
 * Audit event taxonomy (dot-namespaced). Every PHI read/write path emits one
 * of these via @medpass/audit. Adding an action here is reviewed like an API
 * change — dashboards and audit-completeness tests key off these names.
 */
export const AUDIT_ACTIONS = [
  "auth.otp_requested",
  "auth.otp_verified",
  "auth.otp_failed",
  "auth.otp_locked",
  "auth.session_created",
  "auth.session_refreshed",
  "auth.session_revoked",
  "auth.device_login_succeeded",
  "auth.device_login_failed",
  "auth.device_trust_revoked",
  "auth.step_up_requested",
  "auth.step_up_verified",
  "auth.step_up_failed",
  "profile.created",
  "profile.updated",
  "profile.viewed_by_caregiver",
  "profile.claim_invited",
  "profile.claim_invite_cancelled",
  "profile.claimed",
  "consent.granted",
  "consent.revoked",
  "consent.enforced",
  "caregiver.invited",
  "caregiver.accepted",
  "caregiver.scope_changed",
  "caregiver.revoked",
  "caregiver.access_used",
  "caregiver.dependent_created",
  "caregiver.granted_on_claim",
  "allergy.created",
  "allergy.updated",
  "allergy.deleted",
  "condition.created",
  "condition.updated",
  "condition.deleted",
  "immunization.created",
  "immunization.updated",
  "immunization.deleted",
  "procedure.created",
  "procedure.updated",
  "procedure.deleted",
  "family_history.created",
  "family_history.updated",
  "family_history.deleted",
  "emergency_contact.created",
  "emergency_contact.updated",
  "emergency_contact.deleted",
  "organization.created",
  "organization.updated",
  "organization.deleted",
  "organization.merged",
  "organization.verified",
  "glucose_reading.created",
  "glucose_reading.deleted",
  "blood_pressure_reading.created",
  "blood_pressure_reading.deleted",
  "weight_reading.created",
  "weight_reading.deleted",
  "checkup_record.created",
  "checkup_record.deleted",
  "prescription.created",
  "prescription.deleted",
  "prescription_item.created",
  "prescription_item.updated",
  "prescription_item.deleted",
  "prescription_item.started",
  "practitioner.created",
  "practitioner.updated",
  "practitioner.merged",
  "practitioner.verified",
  "practitioner.deleted",
  "report.created",
  "report.deleted",
  "report_value.created",
  "report_value.deleted",
  "diagnostic_report.created",
  "diagnostic_report.updated",
  "diagnostic_report.deleted",
  "diagnostic_result.created",
  "diagnostic_result.corrected",
  "diagnostic_result.deleted",
  "observation.created",
  "observation.deleted",
  "measurement_device.created",
  "measurement_device.updated",
  "measurement_device.deleted",
  "encounter.created",
  "encounter.updated",
  "encounter.deleted",
  "medication.created",
  "medication.updated",
  "medication.status_changed",
  "medication.deleted",
  "medication.list_viewed",
  "medication.refill_recorded",
  "medication.refill_plan_updated",
  "refill_plan.updated",
  "dose.recorded",
  "dose.correction_notice_created",
  "document.upload_authorized",
  "document.upload_completed",
  "document.downloaded",
  // Documents V2 (docs_v2/05 §5): a document is a set of pages, so the
  // lifecycle is per-document plus per-page rather than one upload event.
  "document.created",
  "document.pages_authorized",
  "document.page_completed",
  "document.updated",
  "document.deleted",
  "document.classified",
  "extraction.candidate_confirmed",
  "extraction.candidate_rejected",
  "extraction.materialized",
  "extraction.processed",
  "extraction.field_confirmed",
  "extraction.field_rejected",
  "safety.evaluation_completed",
  "finding.viewed",
  "finding.acknowledged",
  "finding.action_recorded",
  "share.created",
  "share.accessed",
  "share.revoked",
  "notification.preferences_updated",
  "notification.dismissed",
  "notification.channel_revoked",
  /** V2 Phase 6 (docs_v2/06 P6-4): a caregiver-facing kind was queued for dispatch. */
  "notification.caregiver_queued",
  /** V2 Phase 6 (docs_v2/05 §8): the family dashboard read a profile as a caregiver. */
  "caregiver.family_viewed",
  "data.export_requested",
  "data.deletion_requested",
  "account.erased",
  "admin.audit_searched",
  "admin.users_viewed",
  "admin.login_succeeded",
  "admin.login_failed",
  "admin.mfa_enrolled",
  "admin.session_revoked",
  "admin.duties_changed",
  "admin.catalog_change_proposed",
  "admin.catalog_change_approved",
  "admin.catalog_change_rejected",
  "admin.content_change_proposed",
  "admin.content_change_approved",
  "admin.content_change_rejected",
  "admin.content_translation_proposed",
  "admin.content_translation_approved",
  "admin.content_translation_rejected",
  "admin.job_replayed",
  "admin.share_revoked",
  "admin.findings_viewed",
  "content.enrichment_drafted",
  // V2 Phases 11–14 (ADR-V2-009): provider portals. Every provider read and
  // write carries the organization id in `context`; writes are proposals
  // only — the clinical tables change on the patient's accept.
  "provider.login_failed",
  "provider.session_created",
  "provider.session_revoked",
  "provider.organization_updated",
  "provider.member_added",
  "provider.member_updated",
  "provider.member_removed",
  "provider.onboarding_token_created",
  "provider.link_created",
  "provider.link_revoked",
  "provider.patients_listed",
  "provider.snapshot_viewed",
  "provider.proposal_created",
  "provider.proposal_viewed",
  "provider.proposal_accepted",
  "provider.proposal_rejected",
  /** V2 Phase 8 / 15 (docs_v2/05 §10, docs_v2/08): FHIR export of the patient's own record and the Indian Patient Summary. */
  "fhir.exported",
  "fhir.patient_summary_exported",
  /** V2 Phase 8 (docs_v2/08 §5 M8A/M8B/M8D): ABHA identity and PHR flows. */
  "abha.link_initiated",
  "abha.linked",
  "abha.unlinked",
  "abdm.discovery_requested",
  "abdm.care_contexts_linked",
  "abdm.consent_revoked",
  "abdm.bundle_imported",
  /** V2 Phase 17 (docs_v2/05 §12): test-due schedules and measurement reminders. */
  "test_due.created",
  "test_due.updated",
  "test_due.deleted",
  "notification.measurement_reminders_updated",
  /** V2 admin platform (docs_v2/14 §3): flags, support cases, break-glass, consent audit. */
  "admin.flag_updated",
  "admin.support_case_created",
  "admin.support_case_updated",
  "admin.support_case_note_added",
  "admin.break_glass_granted",
  "admin.break_glass_listed",
  "admin.consent_audit_viewed",
  /** V2 Phase 10 (docs_v2/06 P10-1): the patient answering a suggested clinical relationship. */
  "clinical_relationship.confirmed",
  "clinical_relationship.dismissed",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

/**
 * `provider` (V2 Phase 11) is a clinician, pharmacist or lab technician
 * acting inside an Organization — kept distinct from `system` so "every
 * provider read is audited" is a query, not a scan of system rows.
 */
export type AuditActorType = "patient" | "caregiver" | "admin" | "system" | "share_visitor" | "provider";
