/**
 * Generates the pre-recorded guidance audio (docs/32 TTS fallback for the
 * te/ur browser-voice gap): one MP3 per guidance entry per locale, named
 * `{id}.{locale}.{hash8}.mp3` under `public/audio/guidance/`, plus the typed
 * manifest `lib/guidance-audio-manifest.ts`. Artifacts are committed — this
 * runs on a developer machine, never in CI (`guidance-audio.test.ts` is what
 * CI runs: it fails when dictionary copy drifts from the committed audio).
 *
 * Vendor: Google Cloud Text-to-Speech over REST — the one vendor with
 * voices for all four locales (en-IN/hi-IN/te-IN/ur-IN; Sarvam has no Urdu).
 * Needs an API key with the Text-to-Speech API enabled:
 *
 *   GOOGLE_TTS_API_KEY=... pnpm --filter @medpass/patient-web generate:audio
 *
 * Idempotent: an entry whose joined source text is unchanged (same sha256)
 * keeps its file; orphaned files are deleted. `@medpass/localization` must
 * be built first (`pnpm build` at the repo root does it).
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SUPPORTED_LOCALES, t, type Locale } from "@medpass/localization";
import { GUIDANCE_AUDIO_ENTRIES, type GuidanceAudioId } from "../lib/guidance-audio-entries";

const LANGUAGE_CODE: Record<Locale, string> = { en: "en-IN", hi: "hi-IN", te: "te-IN", ur: "ur-IN" };

/**
 * Pin specific voices here after auditioning them (docs/34: te/ur voice
 * quality needs a native-speaker check before bulk generation). Unset = the
 * vendor's default voice for the language, which is stable enough between
 * runs but not guaranteed forever.
 */
const VOICE_NAME: Partial<Record<Locale, string>> = {};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const audioDir = path.resolve(scriptDir, "../public/audio/guidance");
const manifestPath = path.resolve(scriptDir, "../lib/guidance-audio-manifest.ts");

async function synthesize(apiKey: string, text: string, locale: Locale): Promise<Buffer> {
  const response = await fetch(`https://texttospeech.googleapis.com/v1/text:synthesize?key=${apiKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      input: { text },
      voice: { languageCode: LANGUAGE_CODE[locale], ...(VOICE_NAME[locale] ? { name: VOICE_NAME[locale] } : {}) },
      // Mono 24kHz at a modest rate: guidance sentences, not music — keeps
      // the committed repo weight down. 0.95 speaking rate reads calmer for
      // the docs/01 target listener; the in-app "Slower" toggle goes further.
      audioConfig: { audioEncoding: "MP3", speakingRate: 0.95, sampleRateHertz: 24000 },
    }),
  });
  if (!response.ok) {
    throw new Error(`Text-to-Speech failed for ${LANGUAGE_CODE[locale]} (${response.status}): ${await response.text()}`);
  }
  const { audioContent } = (await response.json()) as { audioContent?: string };
  if (!audioContent) throw new Error(`Empty audioContent for ${LANGUAGE_CODE[locale]}`);
  return Buffer.from(audioContent, "base64");
}

async function main() {
  const apiKey = process.env.GOOGLE_TTS_API_KEY;
  if (!apiKey) {
    console.error("GOOGLE_TTS_API_KEY is not set — see the header of this script.");
    process.exit(1);
  }
  mkdirSync(audioDir, { recursive: true });

  const ids = Object.keys(GUIDANCE_AUDIO_ENTRIES).sort() as GuidanceAudioId[];
  const manifest: Record<string, Record<string, { file: string; textHash: string }>> = {};
  const keep = new Set<string>();
  let generated = 0;

  for (const id of ids) {
    manifest[id] = {};
    for (const locale of SUPPORTED_LOCALES) {
      const text = GUIDANCE_AUDIO_ENTRIES[id].sourceKeys.map((key) => t(locale, key)).join(" ");
      if (text.includes("{")) {
        throw new Error(`Entry "${id}" (${locale}) carries an interpolation param — param-bearing keys are ineligible for pre-generation.`);
      }
      const textHash = createHash("sha256").update(text).digest("hex");
      const file = `${id}.${locale}.${textHash.slice(0, 8)}.mp3`;
      keep.add(file);
      const filePath = path.join(audioDir, file);
      if (!existsSync(filePath)) {
        writeFileSync(filePath, await synthesize(apiKey, text, locale));
        generated += 1;
        console.log(`generated ${file} (${text.length} chars)`);
      }
      manifest[id][locale] = { file, textHash };
    }
  }

  let removed = 0;
  for (const file of readdirSync(audioDir)) {
    if (!keep.has(file)) {
      rmSync(path.join(audioDir, file));
      removed += 1;
      console.log(`removed orphan ${file}`);
    }
  }

  const manifestSource = `import type { Locale } from "@medpass/localization";
import type { GuidanceAudioId } from "./guidance-audio-entries";

/**
 * GENERATED by \`pnpm --filter @medpass/patient-web generate:audio\` — do not
 * edit by hand. Maps each guidance entry to its per-locale MP3 under
 * \`public/audio/guidance/\`. \`textHash\` is the sha256 of the joined source
 * text at generation time; \`guidance-audio.test.ts\` fails CI when the
 * dictionary copy drifts from it, so stale audio can never ship silently.
 */
export interface GuidanceAudioAsset {
  /** File name under /audio/guidance/ — content-addressed (\`{id}.{locale}.{hash8}.mp3\`). */
  file: string;
  /** Full sha256 (hex) of the joined source text the audio was generated from. */
  textHash: string;
}

export const GUIDANCE_AUDIO: Partial<Record<GuidanceAudioId, Record<Locale, GuidanceAudioAsset>>> = ${JSON.stringify(manifest, null, 2)};
`;
  const previous = existsSync(manifestPath) ? readFileSync(manifestPath, "utf8") : "";
  if (previous !== manifestSource) writeFileSync(manifestPath, manifestSource);

  console.log(`done: ${ids.length} entries × ${SUPPORTED_LOCALES.length} locales, ${generated} new, ${removed} orphans removed`);
}

await main();
