import type { Locale } from "@medpass/localization";
import type { GuidanceAudioId } from "./guidance-audio-entries";

/**
 * GENERATED by `pnpm --filter @medpass/patient-web generate:audio` — do not
 * edit by hand. Maps each guidance entry to its per-locale MP3 under
 * `public/audio/guidance/`. `textHash` is the sha256 of the joined source
 * text at generation time; `guidance-audio.test.ts` fails CI when the
 * dictionary copy drifts from it, so stale audio can never ship silently.
 */
export interface GuidanceAudioAsset {
  /** File name under /audio/guidance/ — content-addressed (`{id}.{locale}.{hash8}.mp3`). */
  file: string;
  /** Full sha256 (hex) of the joined source text the audio was generated from. */
  textHash: string;
}

export const GUIDANCE_AUDIO: Partial<Record<GuidanceAudioId, Record<Locale, GuidanceAudioAsset>>> = {};
