import type { VisitSummaryDto } from "./visit-summary.service";

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

/** WhatsApp's lightweight markdown: single asterisks for bold, underscores for italic. */
function bold(text: string): string {
  return `*${text}*`;
}

/**
 * Formats a visit summary as plain text for the patient to hand off via
 * WhatsApp's own share intent (docs/07 screen 29 "WhatsApp text summary") —
 * there's no WhatsApp Business API account to send through server-side
 * (OD-10 blocked), so this is the client's own WhatsApp app sending on the
 * patient's behalf, the same way copying the share link already works,
 * just with the readable content itself instead of a link a recipient
 * without connectivity couldn't open anyway. English only this pass,
 * matching the same simplification the SMS templates and PDF export made.
 */
export function renderVisitSummaryText(summary: VisitSummaryDto): string {
  const lines: string[] = [];
  lines.push(bold(summary.profile.displayName));
  const metaBits = [
    summary.profile.yearOfBirth ? `Born ${summary.profile.yearOfBirth}` : null,
    summary.profile.sex,
    `Generated ${formatDate(summary.generatedAt)}`,
  ].filter(Boolean);
  lines.push(metaBits.join(" · "));
  lines.push("");

  if (summary.allergies) {
    lines.push(bold("Allergies"));
    if (summary.allergies.length === 0) lines.push("None recorded.");
    else for (const a of summary.allergies) lines.push(`- ${a.label} — ${a.severity}${a.reactionNote ? ` (${a.reactionNote})` : ""}`);
    lines.push("");
  }

  if (summary.conditions) {
    lines.push(bold("Conditions"));
    if (summary.conditions.length === 0) lines.push("None recorded.");
    else for (const c of summary.conditions) lines.push(`- ${c.label}${c.note ? ` — ${c.note}` : ""}`);
    lines.push("");
  }

  if (summary.currentMedications) {
    lines.push(bold("Current medicines"));
    if (summary.currentMedications.length === 0) lines.push("No current medicines recorded.");
    else
      for (const m of summary.currentMedications) {
        lines.push(`- ${m.name}${m.strengthLabel ? ` (${m.strengthLabel})` : ""}`);
        if (m.ingredients.length) lines.push(`  ${m.ingredients.join(", ")}`);
        lines.push(`  ${m.instructionSummary}`);
        if (m.prescriberName) lines.push(`  Prescribed by ${m.prescriberName}`);
      }
    lines.push("");
  }

  if (summary.recentChanges) {
    lines.push(bold("Recent changes (last 90 days)"));
    if (summary.recentChanges.length === 0) lines.push("No changes in this period.");
    else
      for (const c of summary.recentChanges) {
        lines.push(`- ${c.medicationName} — ${c.change.replace(/_/g, " ")} (${formatDate(c.occurredAt)})`);
      }
    lines.push("");
  }

  if (summary.unresolvedConcerns) {
    lines.push(bold("Unresolved safety concerns"));
    if (summary.unresolvedConcerns.length === 0) lines.push("None open.");
    else {
      for (const c of summary.unresolvedConcerns) {
        lines.push(`- ${c.category.replace(/_/g, " ")} (${c.severity}) — ${c.summary}`);
      }
      lines.push("This may have been prescribed intentionally. Please confirm with a doctor or pharmacist before changing anything.");
    }
    lines.push("");
  }

  lines.push("Generated by medpass from the patient's own records. Not a prescription or medical advice.");
  return lines.join("\n").trim();
}
