import published from "./published-media.json";

/**
 * Typed access to the published marketing assets (generated by
 * scripts/publish-media.mjs — hashed immutable URLs on assets.medidocs.app).
 * A missing entry means that media is still deferred/gated and the section
 * keeps its PlaceholderMedia.
 */
type PublishedFile = { url: string; hash: string; bytes: number; mime: string };
type PublishedVideoAsset = {
  transcript?: string;
  mp4?: PublishedFile;
  webm?: PublishedFile;
  poster?: PublishedFile;
  url?: string;
  spokenText?: string;
};

const assets = published.assets as Record<string, PublishedVideoAsset>;

export function videoAsset(id: string) {
  const a = assets[id];
  if (!a?.mp4 || !a.webm || !a.poster) return null;
  return {
    sources: [
      { src: a.webm.url, type: "video/webm" },
      { src: a.mp4.url, type: "video/mp4" },
    ],
    poster: a.poster.url,
    transcript: a.transcript,
  };
}

export const OG_IMAGE_URL = assets["og"]?.url ?? null;
export const AUDIO_SAMPLE_URL = assets["audio"]?.url ?? null;
